name: Rust

on: [push, pull_request]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: clippy

    - name: Build allow all warnings
      run: RUSTFLAGS=-Awarnings cargo build --all --no-default-features

    - name: Build no features
      run: cargo build --all --no-default-features

    - name: Build with all features
      run: cargo build --all --all-features

    - name: Build with dom features
      run: cargo build --all --features "with-dom"


    - name: Run tests no features
      run: cargo test --all --no-default-features

    - name: Run tests with dom features
      run: cargo test --all --features "with-dom with-measure"


  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy

  wasm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - uses: browser-actions/setup-firefox@latest
    
      - name: Test firefox version
        run: firefox --version

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run test on wasm bindgen
        run: wasm-pack test --firefox --headless

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - name: Run Benchmark
        run: cargo bench -p sauron-core
