[package]
name = "arc-reactor"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sauron = { path = "../../" }
console_error_panic_hook = "0.1"
log = "0.4"
console_log = { version = "1.0", features = ["color"] }

