[package]
name = "datetime_widget_usage"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sauron = { path = "../../../" }
datetime_widget =  { path = "../datetime_widget" }
log = "0.4"
console_log = "0.2"
console_error_panic_hook = "0.1"
